### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by Gadgetoid** [Gadgetoid/gu-multiverse#1]
* [x] - add display sync, to avoid garbage data throwing things out of whack and requiring a reset
* [ ] - support more display buffer types, PIL image?
* [ ] - support three byte RGB transfers and manage that extra padding byte internally
* [ ] - support RGB565 (2 byte) and RGB332 (1 byte) where bandwidth is *critical* (compile flags?)
* [ ] - more fun examples and docs and such
* [x] - make `multiverse` an installable library?
